### ISSUE TITLE
StackExchange.Redis.RedisConnectionException - Cannot connect to redis server

### ISSUE THREAD

**Issue by Astrofyziky** [mattx264/TC#6]
Error when navigating to _http://localhost:4200/szwagierDashboard_

**Error when**
- TC.Webservice is running
- Redis (5.0.7) server running

**Error Description**
It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

**Error details:**

> StackExchange.Redis.RedisConnectionException
>   HResult=0x80131500
>   Message=It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
>   Source=StackExchange.Redis.StrongName
>   StackTrace:
>    at StackExchange.Redis.ConnectionMultiplexer.<ConnectAsync>d__72.MoveNext() in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 801
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Extensions.Caching.Redis.RedisCache.<ConnectAsync>d__18.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Microsoft.Extensions.Caching.Redis.RedisCache.<GetAndRefreshAsync>d__20.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Extensions.Caching.Redis.RedisCache.<GetAsync>d__12.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at TC.WebService.Helpers.DistributedCaching.<GetAsync>d__1`1.MoveNext() in C:\Users\egolo\Source\Repos\TC\TC.WebService\Helpers\DistributedCaching.cs:line 20
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at TC.WebService.Hubs.SzwagierHub.OnConnectedAsync() in C:\Users\egolo\Source\Repos\TC\TC.WebService\Hubs\SzwagierHub.cs:line 47
>    at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<OnConnectedAsync>d__6.MoveNext()
> 
>   This exception was originally thrown at this call stack:
>     StackExchange.Redis.ConnectionMultiplexer.ConnectAsync(string, System.IO.TextWriter) in ConnectionMultiplexer.cs
> 	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
> 	Microsoft.Extensions.Caching.Redis.RedisCache.ConnectAsync(System.Threading.CancellationToken)
> 	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>     ...
>     [Call Stack Truncated]

**Clicking on continue yields:**

StackExchange.Redis.RedisConnectionException: 'It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. ConnectionDisposed on PING'

**Comment by mattx264** [comment]
Try restart your PC.

**Comment by Astrofyziky** [comment]
Issue corrected by restarting PC and turning off VPN.
